### ISSUE TITLE
:bug: Unnecessary Library Imports Causing Errors

### ISSUE THREAD

**Issue by sahandkh1419** [hezarai/hezar#181] opened 2024-10-28 18:56 UTC
When importing Model from hezar.models some unnecessary libraries, such as torchvision, are also imported. This results in an error if these libraries are not present in the environment:
`from hezar.models import Model
`
Error:
`ModuleNotFoundError: No module named 'torchvision'`

Expected Behavior:
Only the essential libraries should be imported, so users do not encounter import errors related to unrelated libraries like torchvision

Proposed Solution:
Please double-check the imports in `hezar/models/__init__.py` to ensure only necessary libraries are loaded when using `from hezar.models import Model`. Specifically, `torchvision` appears to be imported from line 6 of `hezar/models/text_detection/craft/craft_text_detection.py`.

Environment:
```
python==3.10.15
hezar[audio]==0.41.0
```

**Comment by arxyzan** [comment] 2024-10-29 11:03
Hi @sahandkh1419, the issue is fixed in the latest Hezar release (`0.41.1`). Thanks for reporting 🤗.

**Closed** 2024-10-31 07:07 UTC
